# Generated by Django 6.0.1 on 2026-02-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vetmanagementsystem', '0003_remove_client_client_id_client_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
